name: BungeeTabListPlus
main: codecrafter47.bungeetablistplus.BukkitPlugin
version: ${version}
api-version: 1.13
authors:
  - CodeCrafter47
softdepend:
  - Factions
  - Vault
  - VanishNoPacket
  - SuperVanish
  - PremiumVanish
  - PlayerPoints
  - PlaceholderAPI
  - SimpleClans
  - Essentials
  - Multiverse-Core
  - ASkyBlock
  - CMI
